# Generated by Django 5.0 on 2024-09-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contact_contact_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
