# Generated by Django 5.0 on 2024-09-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact_datetime_alter_contact_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='datetime',
        ),
    ]
